// import { AttestationUser } from './user';
// import { SiteUserStatus } from './enums';
    
// export const users: AttestationUser[] = [

//     {"ID":0,
//     "Status": SiteUserStatus.Confirmed,
//     "NominatedByLoginName":"ms\\jackhandy",
//     "NominatedByDisplayName":"Jack Handy",
//     "NominatedDate": new Date("2018-03-21T15:13:28.4"),
//     "ConfirmedByLoginName":null,
//     "ConfirmedByDisplayName":null,
//     "ConfirmedDate": new Date("2018-03-21T15:13:28.4"),
//     "UserIsInvalid": false,
//     "SiteID":1552,"Url":null,
//     "User":{
//         "LoginName":"basplun1",
//         "EID":null,
//         "EmailAddress":null,
//         "DisplayName":"Keller, John",
//         "FirstName":null,
//         "LastName":null,
//         "IsAdmin" :false,
//         "SearchName":null,
//         "JobTitle":null,
//         "DivisionDescription":null},
//     "Role":{"ID":1,"Name":null}},

//     {"ID":0,
//     "Status": SiteUserStatus.Confirmed,
//     "NominatedByLoginName":"ms\\jackhandy",
//     "NominatedByDisplayName":"Steve Gudvangen",
//     "NominatedDate": new Date("2018-03-21T15:13:28.4"),
//     "ConfirmedByLoginName":null,
//     "ConfirmedByDisplayName":null,
//     "ConfirmedDate": new Date("2018-03-21T15:13:28.4"),
//     "UserIsInvalid": false,
//     "SiteID":1552,"Url":null,
//     "User":{
//         "LoginName":"basplun1",
//         "EID":null,
//         "EmailAddress":null,
//         "DisplayName":"Steve Gudvangen",
//         "FirstName":null,
//         "LastName":null,
//         "IsAdmin" :false,
//         "SearchName":null,
//         "JobTitle":null,
//         "DivisionDescription":null},
//     "Role":{"ID":2,"Name":null}},

//     {"ID":0,
//     "Status": SiteUserStatus.Nominated,
//     "NominatedByLoginName":"ms\\jackhandy",
//     "NominatedByDisplayName":"Jack Handy",
//     "NominatedDate": new Date("2018-03-21T15:13:28.4"),
//     "ConfirmedByLoginName":null,
//     "ConfirmedByDisplayName":null,
//     "ConfirmedDate": null,
//     "UserIsInvalid": false,
//     "SiteID":1552,"Url":null,
//     "User":{
//         "LoginName":"handy",
//         "EID":null,
//         "EmailAddress":null,
//         "DisplayName":"Brochhausen, Beth",
//         "FirstName":null,
//         "LastName":null,
//         "IsAdmin" :false,
//         "SearchName":null,
//         "JobTitle":null,
//         "DivisionDescription":null},
//     "Role":{"ID":3,"Name":null}},

//     {"ID":0,
//     "Status": SiteUserStatus.NotSelected,
//     "NominatedByLoginName":"",
//     "NominatedByDisplayName":"",
//     "NominatedDate": null,
//     "ConfirmedByLoginName":null,
//     "ConfirmedByDisplayName":null,
//     "ConfirmedDate": null,
//     "UserIsInvalid": false,
//     "SiteID":1552,"Url":null,
//     "User":{
//         "LoginName":"",
//         "EID":null,
//         "EmailAddress":null,
//         "DisplayName":null,
//         "FirstName":null,
//         "LastName":null,
//         "IsAdmin" :false,
//         "SearchName":null,
//         "JobTitle":null,
//         "DivisionDescription":null},
//     "Role":{"ID":4,"Name":null}}
// ];